### ISSUE TITLE
Log-likelihood of Gaussian MADE

### ISSUE THREAD

**Issue by pbaljeka** [gpapamak/maf#1]
Hi,
I am not sure I understand the log-likelihood expression for the Gaussian MADE:
https://github.com/gpapamak/maf/blob/master/ml/models/mades.py#L234

is this correct?
I assumed that the log -likelihood would be that of a univariate gaussian with mean mu and var alpha? is my understanding wrong?

**Comment by gpapamak** [comment]
Hi Pallavi,

The total log-likelihood L is the sum of the conditional log-likelihoods. The conditional log likelihood associated with variable input[i] is that of a univariate Gaussian with mean m[i] and precision p[i] (that is, its variance is 1/p[i]). In other words, the total log-likelihood is given by 

L = sum_i { log N(m[i], 1/p[i]) }

which is exactly what the line of code you referenced computes.

I hope that helped.
George

**Comment by pbaljeka** [comment]
Thanks! I didn't see the definiton of u above, i thought it was N(0,1). Thanks!
