### ISSUE TITLE
Preprocessed data

### ISSUE THREAD

**Issue by ioannanikolopoulou** [gpapamak/maf#10]
Hello,

Thank you for the code. 
Could you specify the preprocessing methods you apply in the original datasets (e.g. mnist)? Apart from dequantization, logit and all the functions which are already in the code.

**Comment by gpapamak** [comment]
Hi,

The preprocessing steps are described in Appendix D.2 of the paper (https://arxiv.org/abs/1705.07057).

You can find the preprocessed datasets at Zenodo (https://zenodo.org/record/1161203#.Y3OpB-zP30q), which also contains links to the original datasets. The Zenodo datasets together with the code (which reads them and further preprocesses them) should reproduce exactly the datasets that were used in the experiments of the paper.

I'm afraid I no longer have an exact record of the preprocessing steps that took place between the original datasets and the ones at Zenodo, other than their description in the paper.

**Comment by ioannanikolopoulou** [comment]
Hi,

That's ok, thank you.
