### ISSUE TITLE
Migration to version python3.6.4

### ISSUE THREAD

**Issue by josemanuel22** [gpapamak/maf#11]
Trying to understand the code I realized that it runs in python2, I decided to try to do a mini migration. From what I've seen there are serious compatibility problems with python > 3.6. I've managed to get the code working after a few minor changes in version 3.6.4. (It would be necessary to test the changes exhaustively.) Would be could if you can give me access to push my migration branch.

You can find my code in the fork that I have on my [github](https://github.com/josemanuel22/maf)

**Comment by gpapamak** [comment]
Fixed by PR https://github.com/gpapamak/maf/pull/12
