### ISSUE TITLE
Can you provide the preprocessed datasets?

### ISSUE THREAD

**Issue by rtqichen** [gpapamak/maf#2]
It's unclear how `every attribute with a Pearson correlation coefficient greater than 0.98` are eliminated. As correlation is calculated in pairs, how do you decide which attribute to eliminate?

Thanks.

**Comment by gpapamak** [comment]
Hi Ricky,

The preprocessed datasets have now been uploaded at
https://zenodo.org/record/1161203#.Wmti0XVl8eO

The README has been updated accordingly.

Thanks,
George
