### ISSUE TITLE
Error in log likelihood computation

### ISSUE THREAD

**Issue by vidn** [gpapamak/maf#5]
https://github.com/gpapamak/maf/blob/3239e801aa6d9ab8d1b804f26a31806cc588018a/ml/models/mades.py#L234

The tf.sum term should be tf.sum(self.u ** 2 * tf.exp(self.logp) - self.logp))

**Comment by gpapamak** [comment]
No, your suggestion is incorrect. `self.u ** 2` already includes the scaling by `tt.exp(self.logp)`, since `self.u` is calculated by:
```
self.u = tt.exp(0.5 * self.logp) * (self.input - self.m)
```

**Comment by vidn** [comment]
You are right. I missed that you are computing LL wrt to u...however, then you should not need the "-self.logp" term either because the u random variable should have unit variance (= zero log precision) by definition. logp should be the variance if you compute LL wrt to "x". This is what confused me in the first place...

Agree?

**Comment by gpapamak** [comment]
No, we are computing log likelihood with respect to x. Let me explain:

Let P(x) be a Gaussian with mean m and precision p. The log of P(x) is:

log(P(x)) = -0.5 * log(2*pi) + 0.5 * log(a) - 0.5 * p * (x-m)^2

Now define u = sqrt(p) * (x-m). You can rewrite log(P(x)) as:

log(P(x)) = -0.5 * log(2*pi) + 0.5 * log(a) - 0.5 * u^2

The above is precisely what the code computes.

One more point to help clarify things: as you correctly said, u follows a Gaussian distribution with mean 0 and precision 1. Call this distribution P(u). Its log is:

log(P(u)) = -0.5 * log(2*pi) - 0.5 * u^2

This means you can also write the log probability of x as:

log(P(x)) = log(P(u)) + 0.5 * log(a)

I hope that helps clarify things.

**Comment by vidn** [comment]
Cool! I get it now.

I made a subtle mistake in not accounting for the log det derivative when
going from x to u domain!

Which is funny because that is the whole point of MAF! Sorry about the
confusion! B

tw I really want to commend this MAF idea you came up with :).  It makes a
lot of sense and I think it's neat and computationally not too bad. I am
looking into it for an anomaly detection problem and it looks to be a
promising direction to consider.

Thanks,
Vidyut

**Comment by gpapamak** [comment]
Thanks very much Vidyut! I hope MAF will be useful in your application.

**Comment by vidn** [comment]
George,

I had one more clarification question for you :)

In experiments.py, line 452, you compute the std_error as

std_err = logprobs.std() / np.sqrt(data_split.N)

I am not sure why you have an additional factor of np.sqrt(N) for the
std_error term. Since you report the average logprobs, I am a little
confused.

Can you please elaborate?

Thanks,
Vidyut

**Comment by vidn** [comment]
Never mind. I figured it out :)

Thanks,
Vidyut
