### ISSUE TITLE
How you preprocess your data?

### ISSUE THREAD

**Issue by hehaodele** [gpapamak/maf#7]
I am trying to run your code on POWER, GAS datasets.
The data I download from the link is 'txt' files.
However, in your code, you read from a file called 'data.npy'.
```python
def load_data():
    return np.load(datasets.root + 'power/data.npy')
```

Could you please provide the code to preprocess the data and generate npy files?
Thanks.

**Comment by gpapamak** [comment]
As it says in the README, you need to download the preprocessed datasets from this link:
https://zenodo.org/record/1161203#.Wmtf_XVl8eN
This includes the preprocessed datasets exactly as the code reads them.

The links to the individual datasets link to the original files and not to the preprocessed one. They are only for reference; the code doesn't work with them.

**Comment by hehaodele** [comment]
Thank you!
