### ISSUE TITLE
Updation requested

### ISSUE THREAD

**Issue by StarKnight7** [gpapamak/maf#9]
I'm not an expert but I've been working hard to run this code on google colab. Looks like this is not working with the latest python package. Please make those small changes that are required to run on python3 so that people like me can run this code. Nice paper by the way!

**Comment by gpapamak** [comment]
Hi,

I'm sorry, I don't plan to do this, for two reasons:

- I don't maintain this repository anymore.
- I want this repository to faithfully represent how the experiments in the paper were performed.

If you want a python3 version and you can't adapt it yourself, I suggest you look at a different repository. For example:

https://github.com/bayesiains/nflows

is more up-to-date and contains a nice implementation of MAF.

**Comment by gpapamak** [comment]
Fixed by pull request https://github.com/gpapamak/maf/pull/12
